-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('pb_1_pb')


local PBERROR = protobuf.Descriptor();
local PBERROR_ERROR_CODE_FIELD = protobuf.FieldDescriptor();
local PBERROR_ARGS_FIELD = protobuf.FieldDescriptor();

PBERROR_ERROR_CODE_FIELD.name = "error_code"
PBERROR_ERROR_CODE_FIELD.full_name = ".pbError.error_code"
PBERROR_ERROR_CODE_FIELD.number = 1
PBERROR_ERROR_CODE_FIELD.index = 0
PBERROR_ERROR_CODE_FIELD.label = 2
PBERROR_ERROR_CODE_FIELD.has_default_value = false
PBERROR_ERROR_CODE_FIELD.default_value = 0
PBERROR_ERROR_CODE_FIELD.type = 5
PBERROR_ERROR_CODE_FIELD.cpp_type = 1

PBERROR_ARGS_FIELD.name = "args"
PBERROR_ARGS_FIELD.full_name = ".pbError.args"
PBERROR_ARGS_FIELD.number = 2
PBERROR_ARGS_FIELD.index = 1
PBERROR_ARGS_FIELD.label = 2
PBERROR_ARGS_FIELD.has_default_value = false
PBERROR_ARGS_FIELD.default_value = ""
PBERROR_ARGS_FIELD.type = 9
PBERROR_ARGS_FIELD.cpp_type = 9

PBERROR.name = "pbError"
PBERROR.full_name = ".pbError"
PBERROR.nested_types = {}
PBERROR.enum_types = {}
PBERROR.fields = {PBERROR_ERROR_CODE_FIELD, PBERROR_ARGS_FIELD}
PBERROR.is_extendable = false
PBERROR.extensions = {}

pbError = protobuf.Message(PBERROR)

